### ISSUE TITLE
Check `normaliz` is problematic

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/HeLP#13]
The function `HeLP_Solver` does this:
```
  elif arg[1] = "normaliz" and LoadPackage("normaliz") then
    BindGlobal("HeLP_settings", ["normaliz", h2, h3, h4]);
    Info( HeLP_Info, 1, "'normaliz' will be used from now on.");
  elif arg[1] = "normaliz" and LoadPackage("normaliz") = fail then
    BindGlobal("HeLP_settings", [h1, h2, h3, h4]);
    Info( HeLP_Info, 1, "The executable 'BNmzCone' (from normaliz) was not found.\nPlease install normaliz. See the manual of the package NormalizInterface.\nThe calculations will be performed as before.");

```
But this is bad if `NormalizInterface` is used: because it only uses a shared library `libnormaliz`, and no `normaliz` executable is necessary installed or required by an otherwise fully working `NormalizInterface`.

So this check would then prevent a user from activating these settings, even though the user *knows* they work.

Instead, just check if `NormalizInterface` was loaded? Or, even better, just let the user pick whatever they want, and then issue a helpful error whenever zsolve/normaliz really were supposed to be called and it didn't work.

**Comment by margollo** [comment]
Thanks for noting! When we release a new version, we will take care of that

**Comment by fingolfin** [comment]
@margollo if you are reading this: I tried to answer your email but it is impossible, I get an error as reply:

> Your email couldn't be forwarded from REDACTED to another email address.

> Your message couldn't be delivered. Despite repeated attempts to contact the recipient's email system it didn't respond.

**Comment by margollo** [comment]
Hi Max,

Das ist sehr seltsam. Ich habe deine Mail gestern bekommen und gehe sie gerade durch. Antworte später im Detail, ob ich irgendwelche Probleme hatte.

Alles Gute,
Leo



________________________________
From: Max Horn ***@***.***>
Sent: Friday, October 6, 2023 2:12 PM
To: gap-packages/HeLP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gap-packages/HeLP] Check `normaliz` is problematic (Issue #13)


The function HeLP_Solver does this:

  elif arg[1] = "normaliz" and LoadPackage("normaliz") then
    BindGlobal("HeLP_settings", ["normaliz", h2, h3, h4]);
    Info( HeLP_Info, 1, "'normaliz' will be used from now on.");
  elif arg[1] = "normaliz" and LoadPackage("normaliz") = fail then
    BindGlobal("HeLP_settings", [h1, h2, h3, h4]);
    Info( HeLP_Info, 1, "The executable 'BNmzCone' (from normaliz) was not found.\nPlease install normaliz. See the manual of the package NormalizInterface.\nThe calculations will be performed as before.");



But this is bad if NormalizInterface is used: because it only uses a shared library libnormaliz, and no normaliz executable is necessary installed or required by an otherwise fully working NormalizInterface.

So this check would then prevent a user from activating these settings, even though the user knows they work.

Instead, just check if NormalizInterface was loaded? Or, even better, just let the user pick whatever they want, and then issue a helpful error whenever zsolve/normaliz really were supposed to be called and it didn't work.

**Comment by margollo** [comment]
Issue solved in version 4 of the package
